[package]
name = "chip8emu"
version = "0.1.0"
authors = ["Aaditya Sahay <aadityasahay@economist.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand= "0.5"
direct-gui = "0.1"
minifb = "0.14"